/*
 * Copyright (c) 2011-2014 Samsung Electronics Co., Ltd All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef __TIZEN_LOCATION_GEOFENCE_MANAGER_DOC_H__
#define __TIZEN_LOCATION_GEOFENCE_MANAGER_DOC_H__

/**
 * @ingroup CAPI_LOCATION_FRAMEWORK
 * @defgroup CAPI_GEOFENCE_MANAGER_MODULE Geofence Manager
 * @brief This Geofence Manager API provides service related to geofence(geo-fence).
 *
 * @section CAPI_GEOFENCE_MANAGER_MODULE_HEADER Required Header
 *   \#include <geofence_manager.h>
 *
 * @section CAPI_GEOFENCE_MANAGER_MODULE_OVERVIEW Overview
 * This Geofence Manager API provides service related to geofence(geo-fence). A geofence is a virtual perimeter for a real-world geographic area.
 * This API provides functions to set geofence with geopoint, MAC address of Wi-Fi and Bluetooth address. And, notifications on events like changing in service status are provided.
 *
 * There are two kinds of places and fences:
 * - Public places and fences that are created by MyPlace app can be used by all apps.
 * - Private places and fences that are created by specified app can be used by the same app.
 *
 * Notifications can be received about the following events:
 * - Zone in when a device enters a specific area
 * - Zone out when a device exits a specific area
 * - Results and errors for each event requested to geofence module
 *
 * The Geofence manager has the following properties:
 * - geofence type
 * - status
 * - 'Service state change' callback
 *
 * The geofence type property of geofence manager (#geofence_type_e) specified the type of virtual perimeter.
 *
 * The status property describes the current state and duration of a geofence.
 * state (#geofence_state_e) can be uncertain, in, or out.
 *
 * @section CAPI_GEOFENCE_MANAGER_MODULE_FEATURE Related Features
 * This API is related with the following features:\n
 *  - http://tizen.org/feature/location\n
 *  - http://tizen.org/feature/location.geofence\n
 *
 * It is recommended to design feature related codes in your application for reliability.\n
 *
 * You can check if a device supports the related features for this API by using @ref CAPI_SYSTEM_SYSTEM_INFO_MODULE, thereby controlling the procedure of your application.\n
 *
 * To ensure your application is only running on the device with specific features, please define the features in your manifest file using the manifest editor in the SDK.\n
 *
 * More details on featuring your application can be found from <a href="../org.tizen.mobile.native.appprogramming/html/ide_sdk_tools/feature_element.htm"><b>Feature Element</b>.</a>
 *
 */

/**
 * @ingroup CAPI_GEOFENCE_MANAGER_MODULE
 * @defgroup CAPI_GEOFENCE_MODULE Geofence
 * @brief The Geofence defines a virtual perimeter.
 *
 *
 * @section CAPI_GEOFENCE_MODULE_HEADER Required Header
 *   \#include <geofence_manager.h>
 *
 * @section CAPI_GEOFENCE_MODULE_OVERVIEW Overview
 *
 * Geo-fence defines a virtual perimeter for a real-world geographic area.
 * If you create a geofence, you can trigger some activities when a device enters(or exits) the geofences defined by you.
 *
 * You can create a geofence with the information of Geopoint, WiFi, or BT.
 *
 * 1. Geopoint: Gefence is specified by cooridinates (Latitude and Longitude) and Radius\n
 * 2. WIFI: Geofence is specified by BSSID of Wi-Fi access point\n
 * 3. BT: Geofence is specified by Bluetooth address\n
 *
 * Basic service set identification (BSSID)
 * The BSSID is the MAC address of the wireless access point (WAP) generated by combining the 24 bit Organization Unique Identifier (the manufacturer's identity) and the manufacturer's assigned 24-bit identifier for the radio chipset in the WAP.
 *
 *
 * @section CAPI_GEOFENCE_MODULE_FEATURE Related Features
 * This API is related with the following features:\n
 *  - http://tizen.org/feature/location\n
 *  - http://tizen.org/feature/location.geofence\n
 *
 * It is recommended to design feature related codes in your application for reliability.\n
 *
 * You can check if a device supports the related features for this API by using @ref CAPI_SYSTEM_SYSTEM_INFO_MODULE, thereby controlling the procedure of your application.\n
 *
 * To ensure your application is only running on the device with specific features, please define the features in your manifest file using the manifest editor in the SDK.\n
 *
 * More details on featuring your application can be found from <a href="../org.tizen.mobile.native.appprogramming/html/ide_sdk_tools/feature_element.htm"><b>Feature Element</b>.</a>
 *
 */


#endif  /* __TIZEN_LOCATION_GEOFENCE_MANAGER_DOC_H__ */
